spring.application.name=cursosBackend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cursos_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:157443}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Porta q o  Render usa
server.port=${PORT:8080}
